{% set name = "gcloud-aio-bigquery" %}
{% set version = "7.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/gcloud_aio_bigquery-{{ version }}.tar.gz
  sha256: 2cd1c7c9dcb68122ff6187f2b533941c86d954e5312d942c8107aac4d20ea2ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0
    - gcloud-aio-auth >=3.1.0,<6.0.0

test:
  imports:
    - gcloud.aio.bigquery
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/talkiq/gcloud-aio
  summary: Python Client for Google Cloud BigQuery
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - xylar
